version: 2.1

jobs:
  check:
    docker:
      - image: node:18
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            pnpm install
            pnpm rome check ./src
            pnpm rome format ./src

workflows:
  version: 2
  rome: 
    jobs:
      - check:
          pre-steps:
            - run:
                command: curl -fsSL "https://github.com/pnpm/pnpm/releases/latest/download/pnpm-linuxstatic-x64" -o /bin/pnpm; chmod +x /bin/pnpm;