version: 2.1

jobs:
  check:
    docker:
      - image: node:18
    working_directory: ~/project
    steps:
      - checkout
      - run:
          command: |
            npm install
            npx rome check ./src
            npx rome lint ./src

workflows:
  version: 2
  rome: 
    jobs:
      - check