version: 2.1

jobs:
  check:
    docker:
      - image: node:18
    working_directory: ~/clip-pwa
    steps:
      - checkout
      - run:
          command: |
            npx rome check ./src
            npx rome lint ./src

workflows:
  version: 2
  rome: 
    jobs:
      - check:
         pre-steps:
           - run:
               command: npm install