name: Bun

on:
  push:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          
      - name: Run Install
        run: bun install

      - name: Run linter
        run: bun run lint

      - name: Run tests
        run: bun run test

      - name: Run build
        run: bun run build
